# -*- coding: utf-8 -*-
"""FUTURE_DS_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tLfbglkOqw81B0fERfwr9FCOKTta4p_j
"""

from google.colab import files
import pandas as pd

# Upload CSV from your computer
uploaded = files.upload()

# Read uploaded file
df = pd.read_csv('/content/event_feedback.csv')
df.head()

# Check for missing values
print(df.isnull().sum())

# Fill any empty text cells with empty string
df.fillna('', inplace=True)

# Check column names
print(df.columns)

avg_ratings = df.groupby('Event Name')['Rating'].mean().reset_index()
print(avg_ratings)

!pip install textblob
from textblob import TextBlob

def get_sentiment(text):
    return TextBlob(text).sentiment.polarity

df['Likes_Sentiment'] = df['Likes'].apply(get_sentiment)
df['Dislikes_Sentiment'] = df['Dislikes'].apply(get_sentiment)
df['Suggestions_Sentiment'] = df['Suggestions'].apply(get_sentiment)

df[['Likes', 'Likes_Sentiment', 'Dislikes', 'Dislikes_Sentiment']].head()

import seaborn as sns
import matplotlib.pyplot as plt

# Average rating chart
sns.barplot(data=avg_ratings, x='Event Name', y='Rating')
plt.title('Average Rating by Event')
plt.xticks(rotation=45)
plt.show()

# Sentiment distribution
sns.histplot(df['Likes_Sentiment'], kde=True, color='green')
plt.title('Sentiment Distribution for Likes')
plt.show()